spring.application.name=RestaurantReviewApp
# 1. ?????????? ????? reviewsApp.db
spring.datasource.url=jdbc:sqlite:reviewsApp.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# 2. java commands ?? sqlcode
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

# 3. ???????? updates ? ?????????? ??? ????? ???????? ?? ???? ?? .java filles
spring.jpa.hibernate.ddl-auto=update

# 4. ???????? ??? sql queries ??? commandline (?????? ??? ?????? debugging ???? ?? ??????????)
spring.jpa.show-sql=true